"""Single AOT (Ahead-of-Time) driver for both runnable identity kernels in this directory.

`build.sh` compiles two shared libraries, each exporting a C-callable
`_mlir_ciface_identity` (generated by MLIR's `llvm.emit_c_interface`). They both
compute the same m×n identity matrix and differ only in the **calling
convention** — how the result memref crosses the C boundary. This file collapses
what used to be several near-identical drivers into one, with a helper per
convention:

  * identity_return.so  ->  "callee allocates, caller frees"
      The kernel RETURNS a tensor (lowered to a returned memref). C signature:
          void _mlir_ciface_identity(MemRef2D *sret, int64_t m, int64_t n);
      MLIR malloc()s the result buffer and hands it back through the `sret`
      out-pointer; we read it out and then free(result.allocated) ourselves.
      -> see run_return()

  * identity_fill.so  ->  "destination-passing"
      The CALLER allocates the output buffer and passes it in; the kernel fills
      it in place (via bufferization.materialize_in_destination). C signature:
          void _mlir_ciface_identity(MemRef2D *out);
      Nothing is allocated inside MLIR and nothing needs freeing — we just read
      back the NumPy array we handed in.
      -> see run_fill()

Step 1 keeps its own 2-D descriptor here because the shared
common/np_memref.py helper is 1-D.
"""

import ctypes
import numpy as np
from ctypes import c_void_p, c_longlong, c_int64, Structure


class MemRef2D_i32(Structure):
  """ctypes mirror of MLIR's `memref<?x?xi32>` descriptor.

  These five fields are exactly the struct MLIR passes (or returns) for a rank-2
  memref. Note that `offset` and `stride` are measured in ELEMENTS, not bytes.
  """
  _fields_ = [
    ("allocated", c_void_p),        # allocation base pointer — what we free()
    ("aligned",   c_void_p),        # first aligned element  — what we read from
    ("offset",    c_longlong),      # elements from `aligned` to element [0, 0]
    ("shape",     c_longlong * 2),  # (rows, cols)
    ("stride",    c_longlong * 2),  # (row_stride, col_stride), in elements
  ]


# The "callee allocates" path malloc()s the result inside MLIR's runtime, so we
# must hand the buffer back to the C runtime ourselves. On macOS libc lives in
# libSystem.
_libc = ctypes.CDLL("libSystem.dylib")
_libc.free.argtypes = [c_void_p]
_libc.free.restype = None


def _numpy_to_memref_2d(arr: np.ndarray) -> MemRef2D_i32:
  """Wrap a C-contiguous 2-D int32 array in a MemRef descriptor — zero copy.

  No data is moved: we point `allocated`/`aligned` straight at NumPy's own
  buffer and fill in the row-major shape/strides. The kernel then writes its
  results into the very array the caller is already holding.
  """
  if not arr.flags["C_CONTIGUOUS"]:
    arr = np.ascontiguousarray(arr)
  m, n = arr.shape
  desc = MemRef2D_i32()
  desc.allocated = arr.ctypes.data_as(c_void_p)
  desc.aligned   = desc.allocated
  desc.offset    = 0
  desc.shape[0],  desc.shape[1]  = m, n
  desc.stride[0], desc.stride[1] = n, 1   # row-major: n elems per row, 1 per col
  return desc


def _memref_to_numpy_2d(desc: MemRef2D_i32) -> np.ndarray:
  """Copy a returned MemRef descriptor into an array we own.

  Used by the "callee allocates" convention. The descriptor points at a buffer
  MLIR malloc'd; we build a temporary aliasing view and immediately `.copy()` it
  so our array survives the `free()` that follows. MLIR reports strides in
  ELEMENT units, so we scale by the itemsize (4 bytes for i32) for NumPy, which
  wants byte strides.
  """
  shape   = (desc.shape[0], desc.shape[1])
  strides = (desc.stride[0] * 4, desc.stride[1] * 4)   # elements -> bytes
  view = np.ctypeslib.as_array(
    ctypes.cast(desc.aligned, ctypes.POINTER(ctypes.c_int32)),
    shape=shape,
  )
  return np.lib.stride_tricks.as_strided(view, shape=shape, strides=strides).copy()


def run_fill(lib_path: str, m: int, n: int) -> np.ndarray:
  """Destination-passing: WE allocate the buffer, the kernel fills it in place."""
  lib = ctypes.CDLL(lib_path)
  identity = lib._mlir_ciface_identity
  identity.argtypes = [ctypes.POINTER(MemRef2D_i32)]   # single in/out descriptor
  identity.restype = None

  out = np.zeros((m, n), dtype=np.int32)               # caller-owned buffer
  desc = _numpy_to_memref_2d(out)
  identity(ctypes.byref(desc))                         # kernel writes into `out`
  return out                                           # nothing to free


def run_return(lib_path: str, m: int, n: int) -> np.ndarray:
  """Callee-allocates: the kernel malloc()s and returns the buffer; WE free it."""
  lib = ctypes.CDLL(lib_path)
  identity = lib._mlir_ciface_identity
  # sret out-pointer first, then the two index args (i64 on a 64-bit target).
  identity.argtypes = [ctypes.POINTER(MemRef2D_i32), c_int64, c_int64]
  identity.restype = None

  result = MemRef2D_i32()                              # zero-init; callee fills it
  identity(ctypes.byref(result), m, n)
  arr = _memref_to_numpy_2d(result)                   # copy out BEFORE freeing
  _libc.free(result.allocated)                        # release MLIR's buffer
  return arr


def main():
  M, N = 5, 5
  expected = np.eye(M, N, dtype=np.int32)

  # (label, shared library, runner) for each kernel: identity_fill uses
  # destination-passing (run_fill), identity_return returns a tensor (run_return).
  cases = [
    ("identity_fill.mlir   (caller's buffer)", "./build/identity_fill.so",   run_fill),
    ("identity_return.mlir (returns tensor)",  "./build/identity_return.so", run_return),
  ]

  for label, lib_path, run in cases:
    arr = run(lib_path, M, N)
    np.testing.assert_array_equal(arr, expected)      # both must agree
    print(f"Identity matrix generated successfully — {label}")
    print(arr)


if __name__ == "__main__":
  main()
